### ISSUE TITLE
Core principals

### ISSUE THREAD

**Issue by hjalmers** [sebgroup/ng-components#11]
- [ ] Markup and naming conventions #5 
- [ ] Third party libraries #9 #10
- [ ] Structure and demo #3 #2 
- [ ] ?

**Comment by yousifalraheem** [comment]
- naming convention is settled on `sebng-`
- we decided to build components from scratch and avoid the use of third party libraries for efficiency
- demo is built and published
